name: Bank
services:
  #----------------------------------------------------------------
  gateway:
    image: "chotchip/gateway:v6"
    build:
      context: ../gateway-service/
    container_name: "gateway-container"
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - processing
      - currency-rate
      - currency-rate-service-2
    links:
      - "eureka-server"
    networks:
      - ps
  #----------------------------------------------------------------
  postgresdb:
    image: "postgres:${POSTGRES_VERSION}"
    container_name: "postgres-db-container"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#      - PGDATA= /var/lib/postgresql/data
#    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ps
  #----------------------------------------------------------------
  currency-rate:
    image: "chotchip/currency-rate:v9"
    build:
      context: ../currency-rate/
    container_name: "currency-rate-container-1"
    ports:
      - "8085:8085"
    links:
      - "eureka-server"
    networks:
      - ps
  #----------------------------------------------------------------
  currency-rate-service-2:
    image: "chotchip/currency-rate:v9"
    build:
      context: ../currency-rate/
    container_name: "currency-rate-container-2"
    environment:
      - SERVER_PORT=8087
    ports:
      - "8087:8087"
    links:
      - "eureka-server"
    networks:
      - ps
  #----------------------------------------------------------------
  processing:
    image: "chotchip/processing:v15"
    build:
      context: ../processing/
    container_name: "processing-service-container"
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresdb:5432/processing
      - SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVER= http://kafka-1:9092
    stdin_open: true
    tty: true
    depends_on:
      - postgresdb
    links:
      - "eureka-server"
      - "postgresdb"
      - "kafka-1"
    networks:
      - ps
  #----------------------------------------------------------------
  eureka-server:
    image: "chotchip/eureka-service:v4"
    build:
      context: ../eureka-service/
    container_name: "eureka-server-service-container"
    ports:
      - "8761:8761"
    networks:
      - ps
  #----------------------------------------------------------------
  auth-service:
    image: "chotchip/auth:v2"
    build:
      context: ../auth-service/
    container_name: "auth-container"
    ports:
      - "9000:9000"
    links:
      - "eureka-server"
    networks:
      - ps
  #----------------------------------------------------------------
  #### Kafka
  kafka-1:
    container_name: "kafka-1"
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CREATE_TOPICS= account-events
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=YTKn7teFTqqd2pMhDpJh5Q
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9091
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9090,EXTERNAL://kafka-1:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    networks:
      - ps
  #----------------------------------------------------------------
  processing-log:
    image: "chotchip/processing-log:v5"
    container_name: "processing-log-cnt"
    ports:
      - "8081:8081"
    build:
      context: ../processing-log/
    environment:
      - CLOUD_KAFKA= http://kafka-1:9092
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresdb:5432/account_history
    links:
      - "eureka-server"
      - "kafka-1"
      - "postgresdb"
    depends_on:
      - postgresdb
      - kafka-1
      - eureka-server
    networks:
      - ps


networks:
  ps:
    driver: bridge

